_wandb:
    value:
        cli_version: 0.21.1
        e:
            nrlawfd78f5wifw7qf7hcyga2hgdd0q8:
                codePath: development/selection/Q10/default.py
                codePathLocal: development/selection/Q10/default.py
                cpu_count: 48
                cpu_count_logical: 96
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "316464824320"
                        used: "301470326784"
                email: jzervakis@hotmail.com
                executable: /home/jzerv/miniconda3/envs/lotus/bin/python
                gpu: NVIDIA RTX A6000
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA RTX A6000
                      uuid: GPU-f938a88e-b487-e2a3-1527-1ef495ea56d3
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA RTX A6000
                      uuid: GPU-e72e0e85-e8ec-b2d3-31b6-ca7b1cd9e0a3
                host: gaia-superg-2
                memory:
                    total: "405318529024"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.35
                program: /data/hdd1/users/jzerv/thesis_repo/lotus/development/selection/Q10/default.py
                python: CPython 3.10.16
                root: /data/hdd1/users/jzerv/thesis_repo/lotus
                startedAt: "2025-09-19T13:01:24.165190Z"
                writerId: nrlawfd78f5wifw7qf7hcyga2hgdd0q8
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 75
                - 95
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 75
                - 95
                - 105
            "3":
                - 2
                - 13
            "4": 3.10.16
            "5": 0.21.1
            "6": 4.49.0
            "12": 0.21.1
            "13": linux-x86_64
