queries:
  - id: q1
    class_name: derivation
    task_name: classification
    nlq: "Which team won the game described in the summary: home or visitor?"
    table: datasets/nba/game_summaries.csv
    cols: [summary]
    new_col_name: winner
    new_col_type: str
    lotus_query: "Which team won the game described in the {summary}? Return only *home* or *visitor*."
    palimpzest_query: "Which team won the game described in the `summary`? Return only *home* or *visitor*."
    blendsql_query: "Which team won the game described in the {summary}? Return only *home* or *visitor*."
    evaluation_cols: [sportsett_id, summary, win_home_or_vis]

  - id: q4
    class_name: derivation
    task_name: reasoning
    nlq: "Return points scored by the winner team"
    table: datasets/nba/game_summaries.csv
    cols: [summary]
    lotus_query: "Return points scored by the winner team in the game described in the {summary}. Return only the number of points."
    new_col_name: winner_points
    new_col_type: int
    palimpzest_query: "Return points scored by the winner team in the game described in the `summary`. Return only the number of points."
    blendsql_query: "Return points scored by the winner team in the game described in the {summary}. Return only the number of points."
    evaluation_cols: [sportsett_id, summary, winner_points]

  - id: q7
    class_name: derivation
    task_name: extraction
    nlq: "Return points scored by a specific player mentioned in a game summary"
    table: datasets/nba/players_summaries.csv
    cols: [player_name, summary]
    lotus_query: "Return points scored by {player_name} in the game described in the {summary}. Return only the number of points."
    new_col_name: player_points
    new_col_type: int
    palimpzest_query: "Return points scored by `player_name` in the game described in the `summary`. Return only the number of points."
    blendsql_query: "Return points scored by {player_name} in the game described in the {summary}. Return only the number of points."
    evaluation_cols: [sportsett_id, player_name, summary, points]

  - id: q10
    class_name: derivation
    task_name: external_knowledge
    nlq: "Return the birthplace of a specific player"
    table: datasets/nba/all_seasons.csv
    cols: [player_name]
    lotus_query: "Return the birthplace of {player_name}. Return only the name of the country."
    new_col_name: birthplace
    new_col_type: str
    palimpzest_query: "Return the birthplace of `player_name`. Return only the name of the country."
    blendsql_query: "Return the birthplace of {player_name}. Return only the name of the country."
    evaluation_cols: [player_name, country]

  - id: q13
    class_name: selection
    task_name: classification
    nlq: "Did the team win the game?"

    table: datasets/nba/teams_summaries.csv
    cols: [team, summary]

    filtering_col: is_winner
    evaluation_cols: [team, summary, is_winner]

    lotus_query: "The {team} won the game described by {summary}."
    palimpzest_query: "The `team` won the game described by `summary`."

  - id: q14
    class_name: selection
    task_name: classification
    nlq: "Did the team lost the game?"

    table: datasets/nba/teams_summaries.csv
    cols: [team, summary]

    filtering_col: is_loser
    evaluation_cols: [team, summary, is_loser]

    lotus_query: "The {team} lost the game described by {summary}."
    palimpzest_query: "The `team` lost the game described by `summary`."

  - id: q15
    class_name: selection
    task_name: classification
    nlq: "Does the summary mentions the player?"

    table: datasets/nba/players_summaries_all.csv
    cols: [player_name, summary]

    filtering_col: is_mentioned
    evaluation_cols: [player_name, summary, is_mentioned]

    lotus_query: "The summary {summary} mentions the player {player_name}."
    palimpzest_query: "The summary `summary` mentions the player `player_name`."

  - id: q16
    class_name: selection
    task_name: reasoning
    nlq: "The total points (sum) scored by both teams played in the game is greater than 180?"

    table: datasets/nba/game_summaries.csv
    cols: [summary]

    filtering_col: total_points_gt_180
    evaluation_cols: [summary, total_points_gt_180]

    lotus_query: "The total points (sum) scored by both teams played in the game described by {summary} is greater than 180."
    palimpzest_query: "The total points (sum) scored by both teams played in the game described by `summary` is greater than 180."

  - id: q17
    class_name: selection
    task_name: reasoning
    nlq: "Was the winning margin double-digit?"

    table: datasets/nba/game_summaries.csv
    cols: [summary]

    filtering_col: double_digit_margin
    evaluation_cols: [summary, double_digit_margin]

    lotus_query: "The winning margin of game described by {summary} was double-digit."
    palimpzest_query: "The winning margin of game described by `summary` was double-digit."

  - id: q18
    class_name: selection
    task_name: reasoning
    nlq: "Did the player scored over 20 points in the game?"

    table: datasets/nba/players_summaries.csv
    cols: [summary, player_name]

    filtering_col: points_gt_20
    evaluation_cols: [summary, player_name, points_gt_20]

    lotus_query: "The player {player_name} scored over 20 points in the game described by the {summary}."
    palimpzest_query: "The player `player_name` scored over 20 points in the game described by the `summary`."


  - id: q19
    class_name: selection
    task_name: external_knowledge
    nlq: "The player's height is less than 200cm."

    table: datasets/nba/players_info.csv
    cols: [player_name]

    filtering_col: height_lt_200
    evaluation_cols: [player_name, height_lt_200]

    lotus_query: "The height of {player_name} is less than 200cm."
    palimpzest_query: "The height of `player_name` is less than 200cm."

  - id: q20
    class_name: selection
    task_name: external_knowledge
    nlq: "Was the player born in USA?"

    table: datasets/nba/players_info.csv
    cols: [player_name]

    filtering_col: born_in_america
    evaluation_cols: [player_name, born_in_america]

    lotus_query: "The player {player_name} was born in United States of America."
    palimpzest_query: "The player `player_name` was born in United States of America."

  - id: q21
    class_name: selection
    task_name: external_knowledge
    nlq: "Was the player picked in the first draft round?"

    table: datasets/nba/players_info.csv
    cols: [player_name]

    filtering_col: first_round_drafted
    evaluation_cols: [player_name, first_round_drafted]

    lotus_query: "The player {player_name} was picked in the first draft round."
    palimpzest_query: "The player `player_name` was picked in the first draft round."

  - id: q22
    class_name: join
    task_name: classification
    nlq: "The summary mentions a specific player"

    table_left: datasets/nba/join_tables/summary_mentions_player/case_3/summaries.csv
    cols_left: [sportsett_id, summary]
    left_key: summary

    table_right: datasets/nba/join_tables/summary_mentions_player/case_3/players.csv
    cols_right: [player_name]
    right_key: player_name

    evaluation_table: datasets/nba/join_tables/summary_mentions_player/case_3/ground_truth.csv
    evaluation_cols: [sportsett_id, summary, player_name]

    lotus_query: "The summary {summary} mentions the player {player_name}."
    blendsql_query: "The summary {summary} mentions the player {player_name}."

  - id: q23
    class_name: join
    task_name: classification
    nlq: "The summary mentions a specific team"

    table_left: datasets/nba/join_tables/summary_mentions_team/case_2/summaries.csv
    cols_left: [sportsett_id, summary]
    left_key: summary

    table_right: datasets/nba/join_tables/summary_mentions_team/case_2/teams.csv
    cols_right: [team_name]
    right_key: team_name

    evaluation_table: datasets/nba/join_tables/summary_mentions_team/case_2/ground_truth.csv
    evaluation_cols: [sportsett_id, summary, team_name]

    lotus_query: "The summary {summary} mentions the team {team_name}."
    blendsql_query: "The summary {summary} mentions the player {player_name}."

  - id: q24
    class_name: join
    task_name: classification
    nlq: "The team won the game described by the summary."

    table_left: datasets/nba/join_tables/team_won_game/case_2/summaries.csv
    cols_left: [sportsett_id, summary]
    left_key: summary

    table_right: datasets/nba/join_tables/team_won_game/case_2/teams.csv
    cols_right: [team_name]
    right_key: team_name

    evaluation_table: datasets/nba/join_tables/team_won_game/case_2/ground_truth.csv
    evaluation_cols: [sportsett_id, summary, team_name]

    lotus_query: "The team {team_name} won the game described by the summary {summary}."
    blendsql_query: "The team {team_name} won the game described by the summary {summary}."

  - id: q25
    class_name: join
    task_name: reasoning
    nlq: "A specific player scored the most points in the game."

    table_left: datasets/nba/join_tables/player_max_points/case_1/summaries.csv
    cols_left: [sportsett_id, summary]
    left_key: summary

    table_right: datasets/nba/join_tables/player_max_points/case_1/players.csv
    cols_right: [player_name]
    right_key: player_name

    evaluation_table: datasets/nba/join_tables/player_max_points/case_1/ground_truth.csv
    evalution_cols: [sportsett_id, summary, player_name]

    lotus_query: "The player {player_name} scored the most points in the game described by {summary}."
    blendsql_query: "The player {player_name} scored the most points in the game described by {summary}."

  - id: q26
    class_name: join
    task_name: reasoning
    nlq: "A specific player had the most assists in the game."

    table_left: datasets/nba/join_tables/player_max_assists/case_2/summaries.csv
    cols_left: [sportsett_id, summary]
    left_key: summary

    table_right: datasets/nba/join_tables/player_max_points/case_2/players.csv
    cols_right: [player_name]
    right_key: player_name

    evaluation_table: datasets/nba/join_tables/player_max_assists/case_2/ground_truth.csv
    evaluation_cols: [sportsett_id, summary, player_name]

    lotus_query: "The player {player_name} had the most assists in the game described by {summary}."
    blendsql_query: "The player {player_name} had the most assists in the game described by {summary}."

  - id: q27
    class_name: join
    task_name: reasoning
    nlq: "A specific player had the most rebounds in the game."

    table_left: datasets/nba/join_tables/player_max_rebounds/case_2/summaries.csv
    cols_left: [sportsett_id, summary]
    left_key: summary

    table_right: datasets/nba/join_tables/player_max_points/case_2/players.csv
    cols_right: [player_name]
    right_key: player_name

    evaluation_table: datasets/nba/join_tables/player_max_rebounds/case_2/ground_truth.csv
    evaluation_cols: [sportsett_id, summary, player_name]

    lotus_query: "The player {player_name} had the most tota rebounds in the game described by {summary}."
    blendsql_query: "The player {player_name} had the most tota rebounds in the game described by {summary}."
    
  - id: q28
    class_name: join
    task_name: external_knowledge
    nlq: "Player went to College."

    table_left: datasets/nba/join_tables/player_college/case_2/players.csv
    cols_left: [player_name]
    left_key: player_name

    table_right: datasets/nba/join_tables/player_college/case_2/colleges.csv
    cols_right: [college]
    right_key: college

    evaluation_table: datasets/nba/join_tables/player_college/case_2/ground_truth.csv
    evaluation_cols: [player_name, college]

    lotus_query: "The player {player_name} went to {college}."
    blendsql_query: "The player {player_name} went to {college}."

  - id: q29
    class_name: join
    task_name: external_knowledge
    nlq: "Player was over 22 years old in a specific season."

    table_left: datasets/nba/join_tables/player_over_22/case_2/players.csv
    cols_left: [player_name]
    left_key: player_name

    table_right: datasets/nba/join_tables/player_over_22/case_2/seasons.csv
    cols_right: [season]
    right_key: season

    evaluation_table: datasets/nba/join_tables/player_over_22/case_2/ground_truth.csv
    evaluation_cols: [player_name, season]

    lotus_query: "The player {player_name} was over 22 years old in season {season}."
    blendsql_query: "The player {player_name} was over 22 years old in season {season}."
  
  - id: q30
    class_name: join
    task_name: external_knowledge
    nlq: "Player was born in Country."

    table_left: datasets/nba/join_tables/player_country/case_2/players.csv
    cols_left: [player_name]
    left_key: player_name

    table_right: datasets/nba/join_tables/player_country/case_2/countries.csv
    cols_right: [country]
    right_key: country

    evaluation_table: datasets/nba/join_tables/player_country/case_2/ground_truth.csv
    evaluation_cols: [player_name, country]

    lotus_query: "The player {player_name} was born in {country}."
    blendsql_query: "The player {player_name} was born in {country}."

  - id: q31
    class_name: aggregation
    task_name: reasoning
    nlq: "Which player had the most triple doubles among all given games?"
    table: datasets/nba/game_summaries.csv
    cols: [summary]
    lotus_query: "Which player had the most triple doubles among all given games described by {summary}? Return only the name of the player."
    blendsql_query: "Which player had the most triple doubles among all given games described by {summary}? Return only the name of the player."
