experiment_name: "initial_experiment"

systems: ["lotus"]

llms:
  ollama: 
    - "gemma3:12b"
  # vllm:
  #   - "meta-llama/Llama-3.1-8B-Instruct"

input_sizes: [10]
input_sizes_for_join: [[10, 10]]

quality_exps: True

filters:
  class_name: null
  task_name: null
  query_ids: null