project_name: "SQE_exps"
experiment_name: "experiment_name"

systems: ["lotus"] # lotus, palimpzest or blendsql

dataset: nba # nba or rotten_tomatoes

llms:
  # ollama: 
  #   - "gemma3:12b"
  
  vllm:
    # - "meta-llama/Llama-3.1-8B-Instruct"
    # - "RedHatAI/Llama-3.3-70B-Instruct-quantized.w8a8"
    # - "google/gemma-3-12b-it"
    - "Qwen/Qwen3-8B"

# Quality Input Sizes
# input_sizes: [100]
# input_sizes_for_join: [[10, 10]]

# Scalability Ιnput Sizes
input_sizes: [1000, 2000, 4000]
input_sizes_for_join: [[20, 50], [40, 50], [80, 50]]


quality_exps: True # False (Scalability), True (Quality)
wandb_report: False

filters:
  class_name: null
  task_name: null
  query_ids: null