project_name: "SQE_exps"
experiment_name: "derivation"

systems: ["palimpzest"]

llms:
  # ollama: 
  #   - "gemma3:12b"
  vllm:
    # - "meta-llama/Llama-3.1-8B-Instruct"
    # - "RedHatAI/Llama-3.3-70B-Instruct-quantized.w8a8"
    # - "google/gemma-3-12b-it"
    - "Qwen/Qwen3-8B"

input_sizes: [1000, 2000, 4000]
input_sizes_for_join: [[20, 50], [40, 50], [80, 50]]

quality_exps: False
wandb_report: True

filters:
  class_name: derivation
  task_name: null
  query_ids: null